package gtks

// Lists (GTK2.x) defined for 1 column with strings
// Redefine with 'gtk_server_redefine' if necessary
// FUNCTION_NAME = gtk_list_store_new, NONE, WIDGET, 2, INT, INT
// FUNCTION_NAME = gtk_list_store_append, NONE, NONE, 2, WIDGET, WIDGET
// FUNCTION_NAME = gtk_list_store_set, NONE, NONE, 5, WIDGET, WIDGET, INT, STRING, INT
// FUNCTION_NAME = gtk_list_store_set_value, NONE, NONE, 4, WIDGET, WIDGET, INT, STRING
// FUNCTION_NAME = gtk_list_store_clear, NONE, NONE, 1, WIDGET
// FUNCTION_NAME = gtk_list_store_remove, NONE, BOOL, 2, WIDGET, WIDGET
// FUNCTION_NAME = gtk_list_store_move_before, NONE, NONE, 3, WIDGET, WIDGET, WIDGET
// FUNCTION_NAME = gtk_list_store_move_after, NONE, NONE, 3, WIDGET, WIDGET, WIDGET
// FUNCTION_NAME = gtk_list_store_insert, NONE, NONE, 3, WIDGET, WIDGET, INT
// FUNCTION_NAME = gtk_list_store_insert_with_values, NONE, NONE, 6, WIDGET, WIDGET, INT, INT, STRING, INT
// FUNCTION_NAME = gtk_cell_renderer_text_new, NONE, WIDGET, 0
// FUNCTION_NAME = gtk_tree_view_new, NONE, WIDGET, 0
// FUNCTION_NAME = gtk_tree_view_column_set_title, NONE, NONE, 2, WIDGET, STRING
// FUNCTION_NAME = gtk_tree_view_set_model, NONE, NONE, 2, WIDGET, WIDGET
// FUNCTION_NAME = gtk_tree_view_new_with_model, NONE, WIDGET, 1, WIDGET
// FUNCTION_NAME = gtk_tree_view_column_new, clicked, WIDGET, 0
// FUNCTION_NAME = gtk_tree_view_column_new_with_attributes, clicked, WIDGET, 5, STRING, WIDGET, STRING, INT, NULL
// FUNCTION_NAME = gtk_tree_view_column_pack_start, NONE, NONE, 3, WIDGET, WIDGET, BOOL
// FUNCTION_NAME = gtk_tree_view_append_column, NONE, NONE, 2, WIDGET, WIDGET
// FUNCTION_NAME = gtk_tree_view_set_headers_visible, NONE, NONE, 2, WIDGET, BOOL
// FUNCTION_NAME = gtk_tree_view_set_headers_clickable, NONE, NONE, 2, WIDGET, BOOL
// FUNCTION_NAME = gtk_tree_view_get_selection, NONE, WIDGET, 1, WIDGET
// FUNCTION_NAME = gtk_tree_view_get_hadjustment, NONE, WIDGET, 1, WIDGET
// FUNCTION_NAME = gtk_tree_view_get_vadjustment, NONE, WIDGET, 1, WIDGET
// FUNCTION_NAME = gtk_tree_view_column_set_resizable, NONE, NONE, 2, WIDGET, BOOL
// FUNCTION_NAME = gtk_tree_view_column_set_clickable, NONE, NONE, 2, WIDGET, BOOL
// FUNCTION_NAME = gtk_tree_view_scroll_to_cell, NONE, NONE, 6, WIDGET, WIDGET, WIDGET, BOOL, FLOAT, FLOAT
// FUNCTION_NAME = gtk_tree_view_set_grid_lines, NONE, NONE, 2, WIDGET, INT
// FUNCTION_NAME = gtk_tree_selection_get_selected, NONE, BOOL, 3, WIDGET, NULL, WIDGET
// FUNCTION_NAME = gtk_tree_selection_get_tree_view, NONE, WIDGET, 1, WIDGET
// FUNCTION_NAME = gtk_tree_selection_select_iter, NONE, NONE, 2, WIDGET, WIDGET
// FUNCTION_NAME = gtk_tree_selection_select_path, NONE, NONE, 2, WIDGET, WIDGET
// FUNCTION_NAME = gtk_tree_selection_path_is_selected, NONE, BOOL, 2, WIDGET, WIDGET
// FUNCTION_NAME = gtk_tree_selection_set_mode, NONE, NONE, 2, WIDGET, INT
// FUNCTION_NAME = gtk_tree_model_get, NONE, NONE, 5, WIDGET, WIDGET, INT, PTR_STRING, INT
// FUNCTION_NAME = gtk_tree_model_get_iter, NONE, BOOL, 3, WIDGET, WIDGET, WIDGET
// FUNCTION_NAME = gtk_tree_model_get_string_from_iter, NONE, STRING, 2, WIDGET, WIDGET
// FUNCTION_NAME = gtk_tree_model_get_iter_first, NONE, NONE, 2, WIDGET, WIDGET
// FUNCTION_NAME = gtk_tree_model_iter_next, NONE, BOOL, 2, WIDGET, WIDGET
// FUNCTION_NAME = gtk_tree_path_new_from_string, NONE, WIDGET, 1, STRING
// FUNCTION_NAME = gtk_tree_path_free, NONE, NONE, 1, WIDGET
// FUNCTION_NAME = gtk_tree_path_prev, NONE, BOOL, 1, WIDGET
// FUNCTION_NAME = gtk_tree_path_next, NONE, BOOL, 1, WIDGET
// FUNCTION_NAME = gtk_tree_sortable_set_sort_column_id, NONE, NONE, 3, WIDGET, INT, INT
// FUNCTION_NAME = gtk_tree_store_append, NONE, NONE, 3, WIDGET, WIDGET, NULL
// FUNCTION_NAME = gtk_tree_store_new, NONE, WIDGET, 3, INT, INT, INT
// FUNCTION_NAME = gtk_tree_store_set, NONE, NONE, 7, WIDGET, WIDGET, INT, STRING, INT, STRING, INT
