package gtks

// ENUM_NAME = GTK_WINDOW_TOPLEVEL, 0
// ENUM_NAME = GTK_WINDOW_POPUP, 1
type WindowType int

const (
	WINDOW_TOPLEVEL WindowType = iota
	WINDOW_POPUP
)

// ENUM_NAME = GTK_RELIEF_NORMAL, 0
// ENUM_NAME = GTK_RELIEF_HALF, 1
// ENUM_NAME = GTK_RELIEF_NONE, 2
type ReliefStyle int

const (
	RELIEF_NORMAL ReliefStyle = iota
	RELIEF_HALF
	RELIEF_NONE
)

// ENUM_NAME = GTK_BUTTONBOX_DEFAULT_STYLE, 0
// ENUM_NAME = GTK_BUTTONBOX_SPREAD, 1
// ENUM_NAME = GTK_BUTTONBOX_EDGE, 2
// ENUM_NAME = GTK_BUTTONBOX_START, 3
// ENUM_NAME = GTK_BUTTONBOX_END, 4
// ENUM_NAME = GTK_BUTTONBOX_CENTER, 5
type ButtonBoxStyle int

const (
	BUTTONBOX_DEFAULT_STYLE ButtonBoxStyle = iota
	BUTTONBOX_SPREAD
	BUTTONBOX_EDGE
	BUTTONBOX_START
	BUTTONBOX_END
	BUTTONBOX_CENTER
)

// ENUM_NAME = GTK_POLICY_ALWAYS, 0
// ENUM_NAME = GTK_POLICY_AUTOMATIC, 1
// ENUM_NAME = GTK_POLICY_NEVER, 2
type PolicyType int

const (
	POLICY_ALWAYS PolicyType = iota
	POLICY_AUTOMATIC
	POLICY_NEVER
)

// ENUM_NAME = GTK_SHADOW_NONE, 0
// ENUM_NAME = GTK_SHADOW_IN, 1
// ENUM_NAME = GTK_SHADOW_OUT, 2
// ENUM_NAME = GTK_SHADOW_ETCHED_IN, 3
// ENUM_NAME = GTK_SHADOW_ETCHED_OUT, 4
type ShadowType int

const (
	SHADOW_NONE ShadowType = iota
	SHADOW_IN
	SHADOW_OUT
	SHADOW_ETCHED_IN
	SHADOW_ETCHED_OUT
)

// ENUM_NAME = GTK_JUSTIFY_LEFT, 1
// ENUM_NAME = GTK_JUSTIFY_RIGHT, 2
// ENUM_NAME = GTK_JUSTIFY_CENTER, 3
// ENUM_NAME = GTK_JUSTIFY_FILL, 4
type Justification int

const (
	JUSTIFY_LEFT Justification = iota
	JUSTIFY_RIGHT
	JUSTIFY_CENTER
	JUSTIFY_FILL
)
