package gdk

// ENUM_NAME = GDK_WINDOW_TYPE_HINT_NORMAL, 0
// ENUM_NAME = GDK_WINDOW_TYPE_HINT_DIALOG, 1
// ENUM_NAME = GDK_WINDOW_TYPE_HINT_MENU, 2
// ENUM_NAME = GDK_WINDOW_TYPE_HINT_TOOLBAR, 3
// ENUM_NAME = GDK_WINDOW_TYPE_HINT_SPLASHSCREEN, 4
// ENUM_NAME = GDK_WINDOW_TYPE_HINT_UTILITY, 5
// ENUM_NAME = GDK_WINDOW_TYPE_HINT_DOCK, 6
// ENUM_NAME = GDK_WINDOW_TYPE_HINT_DESKTOP, 7
// ENUM_NAME = GDK_WINDOW_TYPE_HINT_DROPDOWN_MENU, 8
// ENUM_NAME = GDK_WINDOW_TYPE_HINT_POPUP_MENU, 9
// ENUM_NAME = GDK_WINDOW_TYPE_HINT_TOOLTIP, 10
// ENUM_NAME = GDK_WINDOW_TYPE_HINT_NOTIFICATION, 11
// ENUM_NAME = GDK_WINDOW_TYPE_HINT_COMBO, 12
// ENUM_NAME = GDK_WINDOW_TYPE_HINT_DND, 13
type WindowTypeHint int

const (
	WINDOW_TYPE_HINT_NORMAL WindowTypeHint = iota
	WINDOW_TYPE_HINT_DIALOG
	WINDOW_TYPE_HINT_MENU
	WINDOW_TYPE_HINT_TOOLBAR
	WINDOW_TYPE_HINT_SPLASHSCREEN
	WINDOW_TYPE_HINT_UTILITY
	WINDOW_TYPE_HINT_DOCK
	WINDOW_TYPE_HINT_DESKTOP
	WINDOW_TYPE_HINT_DROPDOWN_MENU
	WINDOW_TYPE_HINT_POPUP_MENU
	WINDOW_TYPE_HINT_TOOLTIP
	WINDOW_TYPE_HINT_NOTIFICATION
	WINDOW_TYPE_HINT_COMBO
	WINDOW_TYPE_HINT_DND
)

// ENUM_NAME = GDK_SHIFT_MASK, 0
// ENUM_NAME = GDK_LOCK_MASK, 1
// ENUM_NAME = GDK_CONTROL_MASK, 2
// ENUM_NAME = GDK_MOD1_MASK, 3
// ENUM_NAME = GDK_MOD2_MASK, 4
// ENUM_NAME = GDK_MOD3_MASK, 5
// ENUM_NAME = GDK_MOD4_MASK, 6
// ENUM_NAME = GDK_MOD5_MASK, 7
// ENUM_NAME = GDK_BUTTON1_MASK, 8
// ENUM_NAME = GDK_BUTTON2_MASK, 9
// ENUM_NAME = GDK_BUTTON3_MASK, 10
// ENUM_NAME = GDK_BUTTON4_MASK, 11
// ENUM_NAME = GDK_BUTTON5_MASK, 12
// ENUM_NAME = GDK_SUPER_MASK, 13
// ENUM_NAME = GDK_HYPER_MASK, 14
// ENUM_NAME = GDK_META_MASK, 15
// ENUM_NAME = GDK_RELEASE_MASK, 16
// ENUM_NAME = GDK_MODIFIER_MASK, 17
type ModifierType int

const (
	SHIFT_MASK ModifierType = iota
	LOCK_MASK
	CONTROL_MASK
	MOD1_MASK
	MOD2_MASK
	MOD3_MASK
	MOD4_MASK
	MOD5_MASK
	BUTTON1_MASK
	BUTTON2_MASK
	BUTTON3_MASK
	BUTTON4_MASK
	BUTTON5_MASK
	SUPER_MASK
	HYPER_MASK
	META_MASK
	RELEASE_MASK
	MODIFIER_MASK
)
