package gdks

type WindowTypeHint int

const (
	WINDOW_TYPE_HINT_NORMAL WindowTypeHint = iota
	WINDOW_TYPE_HINT_DIALOG
	WINDOW_TYPE_HINT_MENU
	WINDOW_TYPE_HINT_TOOLBAR
	WINDOW_TYPE_HINT_SPLASHSCREEN
	WINDOW_TYPE_HINT_UTILITY
	WINDOW_TYPE_HINT_DOCK
	WINDOW_TYPE_HINT_DESKTOP
	WINDOW_TYPE_HINT_DROPDOWN_MENU
	WINDOW_TYPE_HINT_POPUP_MENU
	WINDOW_TYPE_HINT_TOOLTIP
	WINDOW_TYPE_HINT_NOTIFICATION
	WINDOW_TYPE_HINT_COMBO
	WINDOW_TYPE_HINT_DND
)
