package glib

type Type uint

// ENUM_NAME = G_TYPE_FUNDAMENTAL_SHIFT, 2
const (
	TYPE_FUNDAMENTAL_SHIFT Type = 2
)

// ENUM_NAME = G_TYPE_INVALID, 0
// ENUM_NAME = G_TYPE_NONE, 4
// ENUM_NAME = G_TYPE_INTERFACE, 8
// ENUM_NAME = G_TYPE_CHAR, 12
// ENUM_NAME = G_TYPE_UCHAR, 16
// ENUM_NAME = G_TYPE_BOOLEAN, 20
// ENUM_NAME = G_TYPE_INT, 24
// ENUM_NAME = G_TYPE_UINT, 28
// ENUM_NAME = G_TYPE_LONG, 32
// ENUM_NAME = G_TYPE_ULONG, 36
// ENUM_NAME = G_TYPE_INT64, 40
// ENUM_NAME = G_TYPE_UINT64, 44
// ENUM_NAME = G_TYPE_ENUM, 48
// ENUM_NAME = G_TYPE_FLAGS, 52
// ENUM_NAME = G_TYPE_FLOAT, 56
// ENUM_NAME = G_TYPE_DOUBLE, 60
// ENUM_NAME = G_TYPE_STRING, 64
// ENUM_NAME = G_TYPE_POINTER, 68
// ENUM_NAME = G_TYPE_BOXED, 72
// ENUM_NAME = G_TYPE_PARAM, 76
// ENUM_NAME = G_TYPE_OBJECT, 80
const (
	TYPE_INVALID Type = iota << TYPE_FUNDAMENTAL_SHIFT
	TYPE_NONE
	TYPE_INTERFACE
	TYPE_CHAR
	TYPE_UCHAR
	TYPE_BOOLEAN
	TYPE_INT
	TYPE_UINT
	TYPE_LONG
	TYPE_ULONG
	TYPE_INT64
	TYPE_UINT64
	TYPE_ENUM
	TYPE_FLAGS
	TYPE_FLOAT
	TYPE_DOUBLE
	TYPE_STRING
	TYPE_POINTER
	TYPE_BOXED
	TYPE_PARAM
	TYPE_OBJECT
)
