package gtk

// ENUM_NAME = GTK_ICON_SIZE_INVALID, 0
// ENUM_NAME = GTK_ICON_SIZE_MENU, 1
// ENUM_NAME = GTK_ICON_SIZE_SMALL_TOOLBAR, 2
// ENUM_NAME = GTK_ICON_SIZE_LARGE_TOOLBAR, 3
// ENUM_NAME = GTK_ICON_SIZE_BUTTON, 4
// ENUM_NAME = GTK_ICON_SIZE_DND, 5
// ENUM_NAME = GTK_ICON_SIZE_DIALOG, 6
type IconSize int

const (
	ICON_SIZE_INVALID IconSize = iota
	ICON_SIZE_MENU
	ICON_SIZE_SMALL_TOOLBAR
	ICON_SIZE_LARGE_TOOLBAR
	ICON_SIZE_BUTTON
	ICON_SIZE_DND
	ICON_SIZE_DIALOG
)
