package gtk

// ENUM_NAME = GTK_WRAP_NONE, 0
// ENUM_NAME = GTK_WRAP_CHAR, 1
// ENUM_NAME = GTK_WRAP_WORD, 2
// ENUM_NAME = GTK_WRAP_WORD_CHAR, 3
type WrapMode int

const (
	WRAP_NONE WrapMode = iota
	WRAP_CHAR
	WRAP_WORD
	WRAP_WORD_CHAR
)

// ENUM_NAME = GTK_TEXT_WINDOW_PRIVATE, 0
// ENUM_NAME = GTK_TEXT_WINDOW_WIDGET, 1
// ENUM_NAME = GTK_TEXT_WINDOW_TEXT, 2
// ENUM_NAME = GTK_TEXT_WINDOW_LEFT, 3
// ENUM_NAME = GTK_TEXT_WINDOW_RIGHT, 4
// ENUM_NAME = GTK_TEXT_WINDOW_TOP, 5
// ENUM_NAME = GTK_TEXT_WINDOW_BOTTOM, 6
type TextWindowType int

const (
	TEXT_WINDOW_PRIVATE TextWindowType = iota
	TEXT_WINDOW_WIDGET
	TEXT_WINDOW_TEXT
	TEXT_WINDOW_LEFT
	TEXT_WINDOW_RIGHT
	TEXT_WINDOW_TOP
	TEXT_WINDOW_BOTTOM
)

// ENUM_NAME = GTK_TEXT_SEARCH_VISIBLE_ONLY, 1
// ENUM_NAME = GTK_TEXT_SEARCH_TEXT_ONLY, 2
type TextSearchFlags int

const (
	TEXT_SEARCH_VISIBLE_ONLY TextSearchFlags = 1 << iota
	TEXT_SEARCH_TEXT_ONLY
)
