package gtk

// ENUM_NAME = GTK_TOOLBAR_ICONS, 0
// ENUM_NAME = GTK_TOOLBAR_TEXT, 1
// ENUM_NAME = GTK_TOOLBAR_BOTH, 2
// ENUM_NAME = GTK_TOOLBAR_BOTH_HORIZ, 3
type ToolbarStyle int

const (
	TOOLBAR_ICONS ToolbarStyle = iota
	TOOLBAR_TEXT
	TOOLBAR_BOTH
	TOOLBAR_BOTH_HORIZ
)
