package gtk

// ENUM_NAME = GTK_TREE_VIEW_GRID_LINES_NONE, 0
// ENUM_NAME = GTK_TREE_VIEW_GRID_LINES_HORIZONTAL, 1
// ENUM_NAME = GTK_TREE_VIEW_GRID_LINES_VERTICAL, 2
// ENUM_NAME = GTK_TREE_VIEW_GRID_LINES_BOTH, 3
type TreeViewGridLines int

const (
	TREE_VIEW_GRID_LINES_NONE TreeViewGridLines = iota
	TREE_VIEW_GRID_LINES_HORIZONTAL
	TREE_VIEW_GRID_LINES_VERTICAL
	TREE_VIEW_GRID_LINES_BOTH
)
