package gtks

// ENUM_NAME = GTK_WIN_POS_NONE, 0
// ENUM_NAME = GTK_WIN_POS_CENTER, 1
// ENUM_NAME = GTK_WIN_POS_MOUSE, 2
// ENUM_NAME = GTK_WIN_POS_CENTER_ALWAYS, 3
// ENUM_NAME = GTK_WIN_POS_CENTER_ON_PARENT, 4
type WindowPosition int

const (
	WIN_POS_NONE WindowPosition = iota
	WIN_POS_CENTER
	WIN_POS_MOUSE
	WIN_POS_CENTER_ALWAYS
	WIN_POS_CENTER_ON_PARENT
)
